version: '3.8'

services:
  mongo:
    image: mongo
    restart: on-failure
    container_name: ssmvit-mongo
    ports:
      - 27117:27017
    environment:
      MONGO_INITDB_DATABASE: ssmvit-demo
    volumes:
      - ./mock:/docker-entrypoint-initdb.d
    networks: 
      server_net:
          aliases: 
            - ssmvit-mongo

  client:
    restart: on-failure
    container_name: ssmvit-demo-client
    ports:
      - 8080:80
    networks:
      - web_net
    build: client

  server:
    build: server
    restart: on-failure
    container_name: ssmvit-demo-server
    ports:
      - 3000:3000
    networks: 
      server_net:
      web_net:
        ipv4_address: 172.16.238.10
        aliases: 
        - ssmvit-server

networks:
  web_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
  server_net: